# Colors (Doom One)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#bbc2cf'

# Normal colors
[colors.normal]
black   = '#282c34'
red     = '#ff6c6b'
green   = '#98be65'
yellow  = '#ecbe7b'
blue    = '#51afef'
magenta = '#c678dd'
cyan    = '#46d9ff'
white   = '#bbc2cf'

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Mononoki Nerd FOnt"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd FOnt"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd FOnt"
style = "Italic"

[font.normal]
family = "Mononoki Nerd FOnt"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 0.925
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

